# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: [ ubuntu-latest ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update packages
        run: |
          sudo apt update

      - name: Install packages
        run: |
          sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel ninja-build
          sudo apt-get -y install valgrind libcunit1 libcunit1-doc libcunit1-dev gcovr
          pip install codecov

      - name: Install Meson
        run: |
          pip3 install --user 'meson>=0.59.0'

      - name: Make Build Directory
        run: mkdir build

      - name: Get Sonarcloud Binaries
        working-directory: build
        run: |
          ../.github/scripts/get_sonarcloud.sh

      - name: Meson Build
        run: |
          meson build

      - name: Build
        working-directory: build
        run: |
          build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output ninja all

      - name: Test
        working-directory: build
        run: |
          ninja test

      - name: Coverage Report Generation
        working-directory: build
        run: |
          ninja coverage
          #ninja coverage-sonarqube ## for now this isn't supported
          gcovr --sonarqube sonarqube.xml -r ..

      - name: Upload SonarCloud
        run: |
          build/sonar-scanner/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dproject.settings=.sonar-project.properties -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Codecov.io
        uses: codecov/codecov-action@v2
        with:
          directory: .
          files: build/meson-logs/coverage.xml
          fail_ci_if_error: true
