# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: tag

on:
  push:
    paths:
      - "CHANGELOG.md" # only try to tag if the CHANGELOG has been updated.
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          fetch-depth: 0
      - name: set up bot
        run: |
          git config --global user.name "xmidt-bot"
          git config --global user.email "$BOT_EMAIL"
      - name: export variables and tag commit
        run: |
          export OLD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | tail -1)
          export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v?\d+.\d+.\d+)\].*/s')
          export BINVER=$(cat meson.build | perl -0777 -ne 'print "v$1" if /.*version\s*:\s*.(\d+.\d+.\d+).\s*,/s')
          export TODAY=`date +'%m/%d/%Y'`
          export NOTES=$(cat CHANGELOG.md | perl -0777 -ne 'print "$ENV{TODAY}\n\n$1\n" if /.*## \[$ENV{TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
          if [[ "$TAG" != "" && "$TAG" != "$BINVER" ]]; then echo "CHANGELOG.md($TAG) and meson.build VERSION($BINVER) do not match"; fi
          if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" && "$TAG" == "$BINVER" ]]; then git tag -a "$TAG" -m "$NOTES"; git push origin --tags; echo $?; fi
